declare module 'react-native-check-notification-enable';
declare module 'react-native-drawer-menu';
declare module 'react-native-shadow';
declare module 'react-native-textarea';
declare module 'react-native-material-ripple';
declare module 'date-format';
declare module 'react-native-floating-action';
declare module 'react-native-animated-loader';
declare module '@react-native-community/checkbox';